---
env: 'docker'

eth:
  url: 'http://zkcream-chain:8545'
  contracts:
    creamFactory: '0x2445BC665aEfca58D2137BAf26A62Edb38cBC274' 
    maciFactory: '0x059e17cEb15EF8470B7184B858D356317518aAB3'  
  
  adminKey: '0x9675f7569e4843509e4b1ed22a4dba4e4092bea1d5aa77d65f5d378f0fc454af'

  faucet:
    address: '0x6bbf87f75c84a18907db471941907899e3266214'
    password: ''
    value: '0x16345785D8A0000'

maci:
  initialVoiceCreditBalance: 100
  signUpDurationInSeconds: 3600 # 1 hour
  votingDurationInSeconds: 3600 # 1 hour
  tallyBatchsize: 4
  messageBatchSize: 4
  quadVoteTallyBatchSize: 4
  voteOptionsMaxLeafIndex: 3

  merkleTrees:
    stateTreeDepth: 4
    messageTreeDepth: 4
    voteOptionTreeDepth: 2

ipfs:
  url: 'http://zkcream-ipfs:5001'

server:
  port: 3000
  host: 'http://zkcream-api:3000'
