---
env: 'prod'

eth:
  url:
  contracts:
    creamFactory:
    maciFactory:

  adminKey:

  faucet:
    address:
    password:
    value:

maci:
  initialVoiceCreditBalance: 100
  signUpDurationInSeconds: 3600 # 1 hour
  votingDurationInSeconds: 3600 # 1 hour
  tallyBatchsize: 4
  messageBatchSize: 4
  quadVoteTallyBatchSize: 4
  voteOptionsMaxLeafIndex: 3

  merkleTrees:
    stateTreeDepth: 4
    messageTreeDepth: 4
    voteOptionTreeDepth: 2

ipfs:
  url:

mongo:
  db: zkcream
  uri: 'mongodb://localhost:27017'

auth:
  saltrounds: 10
  jwt:
    secretOrKey:
    expiration: 432000 # 5 days

server:
  port: 3000
  host: 'http://localhost:3000'
