---
env: 'prod'

eth:
  url:
  contracts:
    creamFactory:
    maciFactory:

  adminKey:

  faucet:
    address:
    password:
    value:

maci:
  initialVoiceCreditBalance: 100
  signUpDurationInSeconds: 3600 # 1 hour
  votingDurationInSeconds: 3600 # 1 hour
  tallyBatchsize: 4
  messageBatchSize: 4
  quadVoteTallyBatchSize: 4
  voteOptionsMaxLeafIndex: 3

  merkleTrees:
    stateTreeDepth: 4
    messageTreeDepth: 4
    voteOptionTreeDepth: 2

ipfs:
  url:

auth:
  saltrounds: 10
  jwt:
    secretOrKey:
    expiration: 86400 # 1 day in seconds

cors:
  origins:
    - 'http://localhost:3000'
    - 'http://localhost:3001'

cookie:
  secure: true

server:
  port: 3000
  host: 'http://localhost:3000'
