---
env: 'test'

eth:
  url: 'http://localhost:8545'
  contracts:
    creamFactory: '0x38cF23C52Bb4B13F051Aec09580a2dE845a7FA35'
    maciFactory: '0x0d8cc4b8d15D4c3eF1d70af0071376fb26B5669b'

  adminKey: '0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3'

  faucet:
    address: '0x627306090abaB3A6e1400e9345bC60c78a8BEf57'
    password: ''
    value: '0xDE0B6B3A7640000'

maci:
  initialVoiceCreditBalance: 100
  signUpDurationInSeconds: 120 # 2 min
  votingDurationInSeconds: 120 # 2 min
  tallyBatchsize: 4
  messageBatchSize: 4
  quadVoteTallyBatchSize: 4
  voteOptionsMaxLeafIndex: 3

  merkleTrees:
    stateTreeDepth: 4
    messageTreeDepth: 4
    voteOptionTreeDepth: 2

ipfs:
  url: 'http://50.19.146.202:5001'
  #url: 'http://localhost:5001'

auth:
  saltrounds: 10
  jwt:
    secretOrKey: 'ashdfjhasdlkjfhalksdjhflak'
    expiration: 432000 # 5 days in seconds

cors:
  origins:
    - 'http://localhost:3000'
    - 'http://localhost:3001'

cookie:
  secure: false

server:
  port: 3000
  host: 'http://localhost:3000'
