version: "3"
services:
  zkcream-ipfs:
    container_name: zkcream-ipfs
    build: ./ipfs
    ports:
      - "5001:5001"
    restart: always

  zkcream-chain:
    container_name: zkcream-ganache
    build:  
      context: ./ganache
    ports:
      - "8545:8545"
    restart: always

  zkcream-api:
    container_name: zkcream-api
    working_dir: /api-server
    build:
      context: ../  
    environment:
     - NODE_ENV=docker  
    command:
        yarn start
    ports:
      - "3000:3000"
    restart: always

  zkcream-nginx:
    container_name: zkcream-nginx
    build:
      context: ./nginx
    environment:
      CHAIN: ganache
    links:
      - zkcream-ipfs
      - zkcream-chain
      - zkcream-api
    ports:
      - "80:80"