version: "3"
services:
  zkcream-ipfs:
    container_name: zkcream-ipfs
    build: ./ipfs
    ports:
      - "5001:5001" # api
    restart: always

  zkcream-ganache:
    container_name: zkcream-ganache
    build:  
      context: ./ganache
    ports:
      - "8545:8545"
    restart: always

  zkcream-api:
    container_name: zkcream-api
    working_dir: /api-server
    build:
      context: ../  
    environment:
     - NODE_ENV=docker  
    command:
        yarn start
    ports:
      - "3000:3000"
    restart: always

  # geth:
  #   build: ./geth
  #   ports:
  #     - "8545:8545"
  #     - "8546:8546"
  #   restart: always

  zkcream-nginx:
    container_name: zkcream-nginx
    build:
      context: ./nginx
    links:
      - zkcream-ipfs
      - zkcream-ganache
      - zkcream-api
    ports:
      - "80:80"

  db:
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - ZK_MONGO_USER=${ZK_MONGO_USER}
      - ZK_MONGO_PASS=${ZK_MONGO_PASS}
      - ZK_MONGO_DB=${ZK_MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/.data:/data/db
      - ./mongo/entry:/docker-entrypoint-initdb.d/
