name: server test

on: [push]

jobs:
  buld:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start container
        run: docker-compose -f "docker/docker-compose.yml" up -d

      - name: SetUp node-version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install -g yarn
          yarn
          yarn build

      - name: Test
        run: |
          yarn test

      - name: Stop container
        if: always()
        run: docker-compose -f "docker/docker-compose.yml" down
